name: Update Metadata on Release

on:
  release:
    types: [published]

concurrency: update_metadata

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          ref: master
      - run: |
          printf "  - sha: $(git rev-parse HEAD)\n    changeNotes: ${{ github.event.release.name }}\n" >> metadata.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Metadata"
          git push
